### ISSUE TITLE
Disaster recovery fails with existing storage volumes from previous charmed mongodb deployment

### ISSUE THREAD

**Issue by canonikamal** [canonical/mongodb-operator#235]
Hello

While testing the Disaster recovery scenario for the Charmed Mongodb, it has been observed the newly launched units with the existing storage volumes from the units simulated to be removed as part of a disaster gets stuck at state "hook failed: "database-peers-relation-changed"".

Steps to reproduce:

1. Deploy mongodb charm with 3 units using cinder storage provider
2. Create a testdb and then write some test data to a collection.
3. Remove the mongodb app but without destroying the storage volumes (i.e without --destroy-storage which is default)
4. Deploy a new mongodb unit with application name (same as the removed one) using the existing storage volume.
5. Newly deployed unit never becomes active and gets stuck at "hook failed: "database-peers-relation-changed"".

Execution and commands used for reference:

```
ubuntu@pc1-infra1:~$ juju deploy mongodb mongodb3 --series=jammy --constraints "instance-type=k8s.medium" --storage mongodb=cinder,20G --debug=true -n3
12:07:59 INFO  juju.cmd supercommand.go:56 running juju [2.9.43 3cb3f8beac4a0b05e10bdfb8014f5666118a269d gc go1.20.4]
12:07:59 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23214/bin/juju", "deploy", "mongodb", "mongodb3", "--series=jammy", "--constraints", "instance-type=k8s.medium", "--storage", "mongodb=cinder,20G", "--debug=true", "-n3"}
12:07:59 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:07:59 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/api"
12:07:59 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/api"
12:07:59 INFO  juju.juju api.go:340 API endpoints changed from [194.169.254.231:17070 252.22.0.1:17070 192.168.4.22:17070] to [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:07:59 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:07:59 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
12:07:59 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
12:07:59 INFO  juju.juju api.go:340 API endpoints changed from [192.168.4.22:17070 252.22.0.1:17070 194.169.254.231:17070] to [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:07:59 DEBUG juju.cmd.juju.application.deployer deployer.go:396 cannot interpret as local charm: file does not exist
12:07:59 DEBUG juju.cmd.juju.application.deployer deployer.go:208 cannot interpret as a redeployment of a local charm from the controller
12:08:00 DEBUG juju.cmd.juju.application.store charmadapter.go:142 cannot interpret as charmstore bundle: jammy (series) != "bundle"
12:08:00 INFO  cmd charm.go:452 Preparing to deploy "mongodb" from the charmhub
12:08:00 INFO  juju.cmd.juju.application.deployer series_selector.go:135 with the user specified series "jammy"
12:08:01 INFO  cmd charm.go:550 Located charm "mongodb" in charm-hub, revision 117
12:08:01 INFO  cmd charm.go:236 Deploying "mongodb3" from charm-hub charm "mongodb", revision 117 in channel 5/stable on jammy
12:08:01 DEBUG juju.api monitor.go:35 RPC connection died
12:08:01 DEBUG juju.api monitor.go:35 RPC connection died
12:08:01 INFO  cmd supercommand.go:544 command finished
ubuntu@pc1-infra1:~$
ubuntu@pc1-infra1:~$ juju remove-application mongodb3
removing application mongodb3
- will detach storage mongodb/6
- will detach storage mongodb/7
- will detach storage mongodb/8
ubuntu@pc1-infra1:~$

ubuntu@pc1-infra1:~$ juju show-storage mongodb/6
mongodb/6:
  kind: filesystem
  life: alive
  status:
    current: detached
    since: 14 Jul 2023 12:21:17Z
  persistent: false
ubuntu@pc1-infra1:~$ juju show-storage mongodb/7
mongodb/7:
  kind: filesystem
  life: alive
  status:
    current: detached
    since: 14 Jul 2023 12:21:31Z
  persistent: false
ubuntu@pc1-infra1:~$
ubuntu@pc1-infra1:~$ juju show-storage mongodb/8
mongodb/8:
  kind: filesystem
  life: alive
  status:
    current: detached
    since: 14 Jul 2023 12:30:35Z
  persistent: false
ubuntu@pc1-infra1:~$ 



ubuntu@pc1-infra1:~$ juju deploy mongodb mongodb3 --series=jammy --constraints "instance-type=k8s.medium" --attach-storage mongodb/6 --debug=true
12:31:59 INFO  juju.cmd supercommand.go:56 running juju [2.9.43 3cb3f8beac4a0b05e10bdfb8014f5666118a269d gc go1.20.4]
12:31:59 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23214/bin/juju", "deploy", "mongodb", "mongodb3", "--series=jammy", "--constraints", "instance-type=k8s.medium", "--attach-storage", "mongodb/6", "--debug=true"}
12:31:59 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:31:59 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/api"
12:31:59 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/api"
12:31:59 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:31:59 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
12:31:59 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
12:31:59 INFO  juju.juju api.go:340 API endpoints changed from [194.169.254.231:17070 252.22.0.1:17070 192.168.4.22:17070] to [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
12:31:59 DEBUG juju.cmd.juju.application.deployer deployer.go:396 cannot interpret as local charm: file does not exist
12:31:59 DEBUG juju.cmd.juju.application.deployer deployer.go:208 cannot interpret as a redeployment of a local charm from the controller
12:32:00 DEBUG juju.cmd.juju.application.store charmadapter.go:142 cannot interpret as charmstore bundle: jammy (series) != "bundle"
12:32:00 INFO  cmd charm.go:452 Preparing to deploy "mongodb" from the charmhub
12:32:01 INFO  juju.cmd.juju.application.deployer series_selector.go:135 with the user specified series "jammy"
12:32:01 INFO  cmd charm.go:550 Located charm "mongodb" in charm-hub, revision 117
12:32:01 INFO  cmd charm.go:236 Deploying "mongodb3" from charm-hub charm "mongodb", revision 117 in channel 5/stable on jammy
12:32:05 DEBUG juju.api monitor.go:35 RPC connection died
12:32:05 DEBUG juju.api monitor.go:35 RPC connection died
12:32:05 INFO  cmd supercommand.go:544 command finished
ubuntu@pc1-infra1:~$ 
```

Error from the juju logs:

```
unit-mongodb3-3: 14:13:22 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-mongodb3-3: 14:13:23 WARNING unit.mongodb3/3.database-peers-relation-changed error: snap "charmed-mongodb" not found
unit-mongodb3-3: 14:13:23 ERROR unit.mongodb3/3.juju-log database-peers:25: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/lib/charms/operator_libs_linux/v1/snap.py", line 278, in _snap
    return subprocess.check_output(_cmd, universal_newlines=True)
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['snap', 'set', 'charmed-mongodb', 'monitor-uri="mongodb://monitor:fZkaEvIMdlTmumpLUoiferexXpae3urt@127.0.0.1/?replicaSet=mongodb3&authSource=admin"']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/./src/charm.py", line 909, in <module>
    main(MongodbOperatorCharm)
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/./src/charm.py", line 271, in _on_mongodb_relation_handler
    self._connect_mongodb_exporter()
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/./src/charm.py", line 599, in _connect_mongodb_exporter
    mongodb_snap.set({"monitor-uri": self.monitor_config.uri})
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/lib/charms/operator_libs_linux/v1/snap.py", line 329, in set
    return self._snap("set", [*args])
  File "/var/lib/juju/agents/unit-mongodb3-3/charm/lib/charms/operator_libs_linux/v1/snap.py", line 280, in _snap
    raise SnapError(
charms.operator_libs_linux.v1.snap.SnapError: Snap: 'charmed-mongodb'; command ['snap', 'set', 'charmed-mongodb', 'monitor-uri="mongodb://monitor:fZkaEvIMdlTmumpLUoiferexXpae3urt@127.0.0.1/?replicaSet=mongodb3&authSource=admin"'] failed with output = ''
unit-mongodb3-3: 14:13:23 ERROR juju.worker.uniter.operation hook "database-peers-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mongodb3-3: 14:13:23 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-mongodb3-3: 14:12:41 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-mongodb3-3: 14:13:28 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-mongodb3-3: 14:13:28 WARNING unit.mongodb3/3.database-peers-relation-changed error: snap "charmed-mongodb" not found
```
Even tried adding more units to the application using below commands but they also end up with the same status:
```
ubuntu@pc1-infra1:~$ juju add-unit mongodb3 --attach-storage mongodb/7 --debug=true
14:08:06 INFO  juju.cmd supercommand.go:56 running juju [2.9.43 3cb3f8beac4a0b05e10bdfb8014f5666118a269d gc go1.20.4]
14:08:06 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23214/bin/juju", "add-unit", "mongodb3", "--attach-storage", "mongodb/7", "--debug=true"}
14:08:06 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
14:08:06 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
14:08:06 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
14:08:06 INFO  juju.juju api.go:340 API endpoints changed from [192.168.4.22:17070 194.169.254.231:17070 252.22.0.1:17070] to [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
14:08:10 DEBUG juju.api monitor.go:35 RPC connection died
14:08:10 INFO  cmd supercommand.go:544 command finished
ubuntu@pc1-infra1:~$ juju add-unit mongodb3 --attach-storage mongodb/8 --debug=true
14:08:23 INFO  juju.cmd supercommand.go:56 running juju [2.9.43 3cb3f8beac4a0b05e10bdfb8014f5666118a269d gc go1.20.4]
14:08:23 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/23214/bin/juju", "add-unit", "mongodb3", "--attach-storage", "mongodb/8", "--debug=true"}
14:08:23 INFO  juju.juju api.go:86 connecting to API addresses: [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
14:08:23 DEBUG juju.api apiclient.go:1152 successfully dialed "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
14:08:23 INFO  juju.api apiclient.go:687 connection established to "wss://194.169.254.231:17070/model/244c5506-df51-4a16-8ee6-cb18ecde26f7/api"
14:08:23 INFO  juju.juju api.go:340 API endpoints changed from [252.22.0.1:17070 194.169.254.231:17070 192.168.4.22:17070] to [194.169.254.231:17070 192.168.4.22:17070 252.22.0.1:17070]
14:08:26 DEBUG juju.api monitor.go:35 RPC connection died
14:08:26 INFO  cmd supercommand.go:544 command finished
ubuntu@pc1-infra1:~$
```

Expectation:
Charmed Mongodb application deployed with same name but older volumes should restore the mongodb to the pre-disaster state.

Thanks & regards
Kamal Bhaskar

**Comment by delgod** [comment]
It is expected behaviour you don't have the correct passwords to access the old database. 
Before attaching storage with old data, you need to sync passwords for all internal users (operator, backup, monitor).
Basically, the correct steps will be:
* Deploy MongoDB charm with three units.
* Create a testdb and then write some test data to a collection.
* Store passwords outside of juju.
* Remove the MongoDB app but without destroying the storage volumes.
* Deploy a new MongoDB unit with the same application name (same as the removed one) using the NEW storage volume.
* Set passwords to values of the old cluster.
* Remove all units with data volumes without removing the application. Downscaling to 0.
* Add a unit with storage from the old cluster.
